---
title: "Get utilization standards and piece size by FMU and township"
author:
- Glen W Armstrong^[Department of Renewable Resources, University of Alberta]
date: "2021-09-10"
output:
  html_document:
    df_print: paged
  word_document:
  pdf_document:
    number_sections: yes
    latex_engine: xelatex
    keep_tex: yes
bibliography: historicalResidueSupply.bib
---

```{r setup, include=FALSE, echo = FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, echo=FALSE, message=FALSE}
setwd("/mnt/chromeos/GoogleDrive/SharedDrives/FES_Data_Sharing_Forestry/Manuscripts/histressupp/analysis")
#setwd("g:/Shared Drives/FES_Data_Sharing_Forestry/Manuscripts/histressupp/analysis")

library(tidyverse)
library(janitor)
# library(ggthemes)
# library(gridExtra)
# library(viridis)
# library(skimr)
# library(scales)
# library(DescTools)
# library(zoo)
# library(ezknitr)
#ezknit(file="analysis/manuscript.Rmd", out_dir="output", fig_dir="myfigs")
```

# Introduction



```{r read data files, echo=FALSE}
util_std <- read.csv(file = '../data/util_std.csv')
piece_size <- read.csv(file = '../data/piece_size.csv')
piece_size <- select(piece_size,-FMA)
fmu_twp <- read.csv(file ='../data/FMU_TWP.csv')
species_prop <- read.csv(file = '../data/species_proportions_full.csv') %>%
  select(TRM,max_species)
spp_lookup <- read.csv(file ='../data/species_lookup.csv')

fmu_twp_c <- fmu_twp
fmu_twp_d <- fmu_twp

fmu_twp_c$CD <- "Conif"
fmu_twp_d$CD <- "Decid"
fmu_twp <- rbind(fmu_twp_c,fmu_twp_d)

#head(util_std)
#head(piece_size)
#head(fmu_twp)

util_piece <-full_join(util_std,piece_size,by=c("FMU","CD"))
util_piece_fmu_twp <- full_join(util_piece,fmu_twp,by=c("FMU","CD"))
util_piece_fmu_twp$piece_size <- signif(1/util_piece_fmu_twp$logspm3,3)
util_piece_fmu_twp_species <- full_join(util_piece_fmu_twp,species_prop,by="TRM")
util_piece_fmu_twp_species <- subset(util_piece_fmu_twp_species, (FMU != "A14") &(FMU != "A15") &(FMU != "W11")& (FMU != "W13"))

subs <- subset(util_piece_fmu_twp, (!is.na(piece_size)) & (!is.na(areaha)) & (CD == "Decid"))
avepieceD <- signif(weighted.mean(subs$piece_size,subs$areaha,na.rm = TRUE),3)

subs <- subset(util_piece_fmu_twp, (!is.na(piece_size)) & (!is.na(areaha)) & (CD == "Conif"))
avepieceC <- signif(weighted.mean(subs$piece_size,subs$areaha,na.rm = TRUE),3)

#avepieceC
#avepieceD

head(util_piece_fmu_twp_species)
#if (util_piece_fmu_twp_species$CD == "Decid") util_piece_fmu_twp_species$max_species <- "popu_tre"
#tabyl(util_piece_fmu_twp_species,FMU,CD,show_na = TRUE)
#if (util_piece_fmu_twp_species$CD == "Decid") util_piece_fmu_twp_species$max_species <- "popu_tre"
#if (util_piece_fmu_twp_species$max_species == "pseu_men") util_piece_fmu_twp_species$max_species <- "pice_gla"

util_piece_fmu_twp_species <- util_piece_fmu_twp_species %>%
  mutate(max_species = case_when(
    CD == "Decid" ~ "popu_tre",
    (CD == "Conif") & (max_species == "popu_tre") ~ "pice_gla",
    (CD == "Conif") & (max_species == "popu_bal") ~ "pice_gla",
    (CD == "Conif") & (max_species == "pseu_men") ~ "pice_gla",
    (CD == "Conif") & (max_species == "") ~ "pice_gla",
    CD == "Conif" ~ max_species
    )
  )

util_piece_fmu_twp_species <- util_piece_fmu_twp_species %>%
  mutate(piece_size = case_when(
    (CD == "Conif") & (is.na(piece_size)) ~ avepieceC,
    (CD == "Decid") & (is.na(piece_size)) ~ avepieceD,
    TRUE ~ piece_size
    )
  )

util_piece_fmu_twp_species <- util_piece_fmu_twp_species %>%
  mutate(stumpht = case_when(
    (CD == "Conif") & (is.na(stumpht)) ~ 30.0,
    (CD == "Decid") & (is.na(stumpht)) ~ 30.0,
    TRUE ~ stumpht
    )
  )

util_piece_fmu_twp_species <- util_piece_fmu_twp_species %>%
  mutate(merch_len = case_when(
    (CD == "Conif") & (is.na(merch_len)) ~ 4.88,
    (CD == "Decid") & (is.na(merch_len)) ~ 4.88,
    TRUE ~ merch_len
    )
  )

util_piece_fmu_twp_species <- util_piece_fmu_twp_species %>%
  mutate(stumpd = case_when(
    (CD == "Conif") & (is.na(stumpd)) ~ 15.0,
    (CD == "Decid") & (is.na(stumpd)) ~ 15.0,
    TRUE ~ stumpd
    )
  )

util_piece_fmu_twp_species <- util_piece_fmu_twp_species %>%
  mutate(topd = case_when(
    (CD == "Conif") & (is.na(topd)) ~ 11.0,
    (CD == "Decid") & (is.na(topd)) ~ 10.0,
    TRUE ~ topd
    )
  )

stuff <- util_piece_fmu_twp_species %>%
  select(max_species,stumpht,stumpd,topd,merch_len,piece_size)

dbhCalcInput <- unique(stuff)

save(dbhCalcInput, file="../data/dbhCalcInput.RData")



#tabyl(util_piece_fmu_twp_species,max_species,CD,show_na = TRUE)
#head(util_piece_fmu_twp_species)

rename(util_piece_fmu_twp_species,stump_d = stumpd)
rename(util_piece_fmu_twp_species,top_d = topd)
rename(util_piece_fmu_twp_species,stump_ht = stumpht)
rename(util_piece_fmu_twp_species,min_len = merch_len)
rename(util_piece_fmu_twp_species,merch_ib_vol = piece_size)


util_piece_fmu_twp_species <- left_join(util_piece_fmu_twp_species,spp_lookup)

rename(util_piece_fmu_twp_species,species = sp)

save(util_piece_fmu_twp_species,file="../data/util_piece_fmu_twp_species.RData")

util_piece_fmu_twp_species
spp_lookup
```

# Literature cited
