---
title: "Taper Models"
author:

- Glen W Armstrong^[Department of Renewable Resources, University of Alberta]

date: "19/03/2021"
output:
  html_document:
    df_print: paged
  word_document: default
  pdf_document:
    number_sections: yes
    latex_engine: xelatex
    keep_tex: yes
bibliography: historicalResidueSupply.bib
---

```{r setup, include=FALSE, echo = FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, echo=FALSE, message=FALSE}
#setwd("g:/Shared drives/FES_Data_Sharing (Forestry)/Manuscripts/Historical Residue Supply/Analysis")
library(tidyverse)
library(ggthemes)
library(gridExtra)
library(viridis)
library(skimr)
library(scales)
library(DescTools)
library(zoo)
```

## Taper

calculates important ratios based on taper functions

```{r parameters}

diameters <- c(
13	,
14	,
15	,
16	,
17	,
18	,
19	,
20	,
21	,
22	,
23	,
24	,
25	,
26	,
27	,
28	,
29	,
30	,
31	,
32	,
33	,
34	,
35	,
36	,
37	,
38	,
39	,
40	,
41	,
42	,
43	,
44	,
45	,
46	,
47	,
48	,
49	,
50	
)

ecozones <- c(4,5,6,9,10,14)
speciesList <- c(",ABIE,LAS,,",",ABIE,BAL,,",",BETU,PAP,PAP,",",LARI,LAR,,",",PICE,ENG,,",",PICE,GLA,,",",PICE,MAR,,",
                 ",PINU,BAN,,",",PINU,CON,LAT,",",POPU,TRE,,",",POPU,BAL,,",",PSEU,MEN,GLA,")
species2 <- c("Fa","Fb","Bw","Lt","Se","Sw","Sb",
              "Pj","Pl","Aw","Pb","Fd")
header <- "Tree_num,Province,Ecozone,Genus,Species,Variety,DBH,Height"
header2 <- "Tree_num,Province,Ecozone,Genus,Species,Variety,DBH,Height,merchVol,topVolRatio,topBarkRatio"

cat(sprintf("%s\n",header),file = "e:/ualberta/bioCalcInput.csv", append = FALSE)
cat(sprintf("%s\n",header2),file = "../data/ratios.csv", append = FALSE)

taperCoefficients <- read.csv(file = '../data/taperCoefficients.csv')
trimAllowance <- 0.05 # m  or 5 cm
minPieceLength <- 2.44 + trimAllowance

treenum <- 0
spcnt <- 0
for (sp in species2) {
  spcnt <- spcnt + 1
  t <- taperCoefficients %>% filter(species == species2[[spcnt]])
  b0 <- t$b0
  b1 <- t$b1
  b2 <- t$b2
  topD <- t$uTopD
#  stumpht <- t$uStumpHt
  stumpht <- 0
  minloglength <- t$uMinlen
  
  db0 <- t$db0
  db1 <- t$db1
  
  for (ez in ecozones){
    for (val in diameters){
      dbh <- val
      dbhib <- (dbh - db0)/db1
      
      height = function(dbh,b0,b1){
        ht <- b0 * dbh^b1
        return(ht)
      }
      
      
      
      taper = function(h,dbh,b0,b1,b2){
        ht <- height(dbh,b0,b1)
        num <- ht - h
        den <- ht - 1.3
        d <- sqrt(dbh^2 * (h/1.3)^(2-b2) * (num/den))
        return(d)
      }
      
      taperTop = function(h,dbh,topD,b0,b1,b2){
        ht <- height(dbh,b0,b1)
        num <- ht - h
        den <- ht - 1.3
        toast <- sqrt(dbh^2 * (h/1.3)^(2-b2) * (num/den)) - topD
        return(toast)
      }
      
      ht <- height(dbh,b0,b1)
      
      merchht <- uniroot(taperTop, dbh=dbh,topD=topD,b0=b0, b1=b1, b2=b2,lower=0,upper=ht)$root
      loglength <- merchht - stumpht
      
      # merchht <- if(sp == "Aw"){
      #   merchht <- 15
      # } else {
      #   merchht <- merchht
      # }
      # 
      
      
      
      
      obArea = function(h){
        r <- taper(h,dbh,b0,b1,b2) 
        r <- r/200
        area <- pi * r^2
        return(area)
      }
      
      ibArea = function(h){
        r <- taper(h,dbh,b0,b1,b2) 
        #  r <- max(0,(r - db0)/db1)
        r <- (r - db0)/db1
        r <- max(0,r/200)
        area <- pi * r^2
        return(area)
      }
      
      obVolume <-
        integrate(obArea,lower=stumpht,upper=merchht)
      
      totalOBVolume <-
        integrate(obArea,lower=0,upper=ht)
      
      totalIBVolume <-
        integrate(Vectorize(ibArea),lower=0,upper=ht)
      
      totalBarkVolume <- totalOBVolume$value - totalIBVolume$value
      
      obVol <- if(loglength < t$uMinlen){
        0
      } else {
        obVolume$value
      }
      
      ibVolume <- 
        integrate(Vectorize(ibArea),lower=stumpht,upper=merchht)
      
      
      
      ibVol <- if(loglength < t$uMinlen){
        0
      } else {
        ibVolume$value
      }
      
      merchVol <- ibVol
      stemBarkVolume <- obVol - ibVol
      topVolume <-  
        integrate(Vectorize(ibArea),merchht,upper=ht)
      topObVol <- integrate(Vectorize(obArea),merchht,upper=ht)
      topBarkVolume <- topObVol$value - topVolume$value 
      
      topVol <- topVolume$value
      top2merchRatio <- topVol/ibVol
    
      
      topBarkRatio <- topBarkVolume/totalBarkVolume
      totalIBVolume
      topVolRatio <- topVolume$value/totalIBVolume$value
      
      topVolume
      top2merchRatio
      logs <- loglength/(4.88 + 0.05)
      toploglength <- ((logs - floor(logs)) * (4.88 + 0.05))
      logs
      toploglength
      logs - floor(logs)
      (logs - floor(logs)) * 4.93
 #     oFile <- file("../data/output.csv")
      treenum <- treenum + 1
      stuff <- paste0(",AB,",ez,speciesList[[spcnt]])
      
      cat(sprintf("%i%s%6.2f%s%6.2f\n",treenum,stuff,dbh,",",ht),
          file = "e:/ualberta/bioCalcInput.csv",append = TRUE)
      cat(sprintf("%i%s%6.2f%s%6.2f%s%f%s%f%s%f\n",treenum,stuff,dbh,",",ht,",",
                  merchVol,",",topVolRatio,",",topBarkRatio),
          file = "../data/ratios.csv",append = TRUE)
    }
  } 
}
#closeAllConnections()
```